import type { AudioAsset } from "@/lib/audio-types";

export const openPlayful001Audio: AudioAsset = {
	name: "open-playful-001",
	dataUri:
		"data:audio/mpeg;base64,SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYwLjMuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAACAAABhgC7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7//////////////////////////////////////////////////////////////////8AAAAATGF2YzYwLjMAAAAAAAAAAAAAAAAkAAAAAAAAAAAAYYQHAAAAAAAAAAAAAAAAAAAA//tAxAAAAAANIAAAAAAAAAA0gAAAAAAAAAAAAAAAAAD/+1DEFIAAAA0gAAAAAAAADSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	duration: 0.261,
	format: "mp3",
	license: "CC0",
	author: "audx",
};
