import { resolveImport } from "../core/alias-resolver.js";
import type { AliasMap, AudxConfig, ThemeConfig } from "../types.js";

/**
 * Generate the `sound-theme.ts` TypeScript source from a theme configuration.
 *
 * The generated file exports:
 * - `SemanticSoundName` — union type of all semantic names present in the themes
 * - `soundThemes` — object mapping theme names to their sound mappings
 * - `play(name)` — plays the mapped sound in the active theme (no-ops for null)
 * - `setSoundTheme(themeName)` — switches the active theme at runtime
 */
export function generate(
	themeConfig: ThemeConfig,
	aliasMap: AliasMap,
	config: AudxConfig,
): string {
	// The generated file lives in libDir (e.g. "src/lib/sound-theme.ts")
	const generatedFilePath = `${config.libDir}/sound-theme.ts`;

	// Collect all unique semantic names across all themes
	const semanticNames = collectSemanticNames(themeConfig);

	// Collect all unique non-null sound file paths across all themes
	const soundPaths = collectSoundPaths(themeConfig);

	// Build import statements for each sound module
	const imports = buildImports(soundPaths, generatedFilePath, aliasMap);

	// Resolve the audio-engine import path
	const audioEngineImport = resolveImport(
		aliasMap,
		generatedFilePath,
		`${config.libDir}/audio-engine.ts`,
	);

	const lines: string[] = [];

	// File header
	lines.push("// This file is auto-generated by audx. Do not edit manually.");
	lines.push("");

	// Audio engine import
	lines.push(`import { playAudio } from "${audioEngineImport}";`);

	// Sound module imports
	for (const { importName, importPath } of imports) {
		lines.push(`import { default as ${importName} } from "${importPath}";`);
	}
	lines.push("");

	// SemanticSoundName type union
	lines.push(buildSemanticSoundNameType(semanticNames));
	lines.push("");

	// soundThemes object
	lines.push(
		buildSoundThemesObject(
			themeConfig,
			soundPaths,
			generatedFilePath,
			aliasMap,
		),
	);
	lines.push("");

	// Runtime state
	lines.push(`let activeTheme = "${themeConfig.activeTheme}";`);
	lines.push("");

	// setSoundTheme function
	lines.push("export function setSoundTheme(themeName: string): void {");
	lines.push("  activeTheme = themeName;");
	lines.push("}");
	lines.push("");

	// play function
	lines.push("export function play(name: SemanticSoundName): void {");
	lines.push("  const theme = soundThemes[activeTheme];");
	lines.push("  if (!theme) return;");
	lines.push("  const asset = theme[name];");
	lines.push("  if (!asset) return;");
	lines.push("  playAudio(asset.dataUri);");
	lines.push("}");
	lines.push("");

	return lines.join("\n");
}

/**
 * Collect all unique semantic names across all themes.
 */
function collectSemanticNames(themeConfig: ThemeConfig): string[] {
	const names = new Set<string>();
	for (const mappings of Object.values(themeConfig.themes)) {
		for (const key of Object.keys(mappings)) {
			names.add(key);
		}
	}
	return Array.from(names).sort();
}

/**
 * Collect all unique non-null sound file paths across all themes.
 */
function collectSoundPaths(themeConfig: ThemeConfig): string[] {
	const paths = new Set<string>();
	for (const mappings of Object.values(themeConfig.themes)) {
		for (const value of Object.values(mappings)) {
			if (value !== null) {
				paths.add(value);
			}
		}
	}
	return Array.from(paths).sort();
}

/**
 * Derive a safe import variable name from a sound file path.
 * e.g. "src/sounds/click-001.ts" → "click001Sound"
 */
function deriveImportName(soundPath: string): string {
	const fileName = soundPath.split("/").pop() ?? soundPath;
	const baseName = fileName.replace(/\.(tsx?|jsx?|mjs|cjs)$/, "");
	// Convert kebab-case to camelCase and append "Sound"
	const camel = baseName
		.split("-")
		.map((part, i) =>
			i === 0
				? part.toLowerCase()
				: part.charAt(0).toUpperCase() + part.slice(1).toLowerCase(),
		)
		.join("");
	return `${camel}Sound`;
}

/**
 * Build import statements for all sound modules.
 */
function buildImports(
	soundPaths: string[],
	generatedFilePath: string,
	aliasMap: AliasMap,
): Array<{ importName: string; importPath: string; originalPath: string }> {
	return soundPaths.map((soundPath) => {
		const importPath = resolveImport(aliasMap, generatedFilePath, soundPath);
		const importName = deriveImportName(soundPath);
		return { importName, importPath, originalPath: soundPath };
	});
}

/**
 * Build the `SemanticSoundName` type union string.
 */
function buildSemanticSoundNameType(semanticNames: string[]): string {
	if (semanticNames.length === 0) {
		return "export type SemanticSoundName = never;";
	}
	const members = semanticNames.map((n) => `"${n}"`).join(" | ");
	return `export type SemanticSoundName = ${members};`;
}

/**
 * Build the `soundThemes` object source code.
 */
function buildSoundThemesObject(
	themeConfig: ThemeConfig,
	soundPaths: string[],
	generatedFilePath: string,
	aliasMap: AliasMap,
): string {
	// Build a lookup from original path → import variable name
	const pathToImportName = new Map<string, string>();
	for (const soundPath of soundPaths) {
		pathToImportName.set(soundPath, deriveImportName(soundPath));
	}

	const lines: string[] = [];
	lines.push(
		"export const soundThemes: Record<string, Record<SemanticSoundName, { dataUri: string } | null>> = {",
	);

	for (const [themeName, mappings] of Object.entries(themeConfig.themes)) {
		lines.push(`  "${themeName}": {`);
		const sortedEntries = Object.entries(mappings).sort(([a], [b]) =>
			a.localeCompare(b),
		);
		for (const [semanticName, soundPath] of sortedEntries) {
			if (soundPath === null) {
				lines.push(`    "${semanticName}": null,`);
			} else {
				const importName = pathToImportName.get(soundPath);
				if (importName) {
					lines.push(`    "${semanticName}": ${importName},`);
				} else {
					lines.push(`    "${semanticName}": null,`);
				}
			}
		}
		lines.push("  },");
	}

	lines.push("};");
	return lines.join("\n");
}
