import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { getInstalledThemes } from "../src/commands/utils.js";

describe("getInstalledThemes", () => {
	let tempDir: string;
	let originalCwd: string;

	beforeEach(() => {
		originalCwd = process.cwd();
		tempDir = join(
			tmpdir(),
			`audio-test-${Date.now()}-${Math.random().toString(36).slice(2)}`,
		);
		mkdirSync(tempDir, { recursive: true });
		process.chdir(tempDir);
	});

	afterEach(() => {
		process.chdir(originalCwd);
		rmSync(tempDir, { recursive: true, force: true });
	});

	it("returns empty array when themes directory does not exist", async () => {
		const themes = await getInstalledThemes();
		expect(themes).toEqual([]);
	});

	it("returns themes from .ts files in the output directory", async () => {
		const outDir = join(tempDir, "src", "audio", "themes");
		mkdirSync(outDir, { recursive: true });

		const moduleContent = [
			"// test-theme — generated by @litlab/audx (do not edit)",
			"// theme: Test Theme",
			'import type { SoundDefinition, SoundPatch } from "@litlab/audx";',
			"",
			'export const click: SoundDefinition = {"source":{"type":"sine"}};',
			"",
			'export const pop: SoundDefinition = {"source":{"type":"sine"}};',
			"",
			"export const _patch: SoundPatch = {",
			'  ...{"name":"Test Theme"},',
			"  sounds: { click, pop },",
			"};",
			"",
		].join("\n");

		writeFileSync(join(outDir, "test-theme.ts"), moduleContent);

		const themes = await getInstalledThemes();
		expect(themes).toHaveLength(1);
		expect(themes[0].name).toBe("Test Theme");
		expect(themes[0].soundCount).toBe(2);
		expect(themes[0].file).toBe("test-theme.ts");
	});

	it("skips index.ts", async () => {
		const outDir = join(tempDir, "src", "audio", "themes");
		mkdirSync(outDir, { recursive: true });

		writeFileSync(
			join(outDir, "index.ts"),
			'export * as core from "./core";\n',
		);
		writeFileSync(
			join(outDir, "core.ts"),
			[
				"// theme: Core",
				'import type { SoundDefinition, SoundPatch } from "@litlab/audx";',
				'export const click: SoundDefinition = {"source":{"type":"sine"}};',
				"export const _patch: SoundPatch = {",
				'  ...{"name":"Core"},',
				"  sounds: { click },",
				"};",
			].join("\n"),
		);

		const themes = await getInstalledThemes();
		expect(themes).toHaveLength(1);
		expect(themes[0].name).toBe("Core");
	});

	it("skips non-.ts files", async () => {
		const outDir = join(tempDir, "src", "audio", "themes");
		mkdirSync(outDir, { recursive: true });

		writeFileSync(join(outDir, "readme.md"), "# hello");

		const themes = await getInstalledThemes();
		expect(themes).toEqual([]);
	});
});
