// Minimal — generated by @litlab/audx (do not edit)
// patch: Minimal
import type { SoundDefinition, SoundPatch } from "@litlab/audx";

export const success: SoundDefinition = {
	source: { type: "sine", frequency: 880 },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.02 },
	gain: 0.08,
};
export const error: SoundDefinition = {
	source: { type: "sine", frequency: { start: 400, end: 200 } },
	envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
	gain: 0.09,
};
export const warning: SoundDefinition = {
	source: { type: "sine", frequency: 660 },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const info: SoundDefinition = {
	source: { type: "sine", frequency: 1100 },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.06,
};
export const click: SoundDefinition = {
	source: { type: "sine", frequency: 1200 },
	envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
	gain: 0.1,
};
export const back: SoundDefinition = {
	source: { type: "sine", frequency: { start: 800, end: 600 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.08,
};
export const enter: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 900 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.09,
};
export const _delete: SoundDefinition = {
	source: { type: "sine", frequency: { start: 500, end: 250 } },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.08,
};
export const copy: SoundDefinition = {
	source: { type: "sine", frequency: 1400 },
	envelope: { attack: 0, decay: 0.01, sustain: 0, release: 0.004 },
	gain: 0.07,
};
export const paste: SoundDefinition = {
	source: { type: "sine", frequency: 1300 },
	envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.005 },
	gain: 0.07,
};
export const scroll: SoundDefinition = {
	source: { type: "sine", frequency: 1500 },
	envelope: { attack: 0, decay: 0.006, sustain: 0, release: 0.002 },
	gain: 0.04,
};
export const hover: SoundDefinition = {
	source: { type: "sine", frequency: 1300 },
	envelope: { attack: 0, decay: 0.008, sustain: 0, release: 0.003 },
	gain: 0.03,
};
export const toggle: SoundDefinition = {
	source: { type: "sine", frequency: 1100 },
	envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
	gain: 0.08,
};
export const notify: SoundDefinition = {
	source: { type: "sine", frequency: 880 },
	envelope: { attack: 0, decay: 0.12, sustain: 0, release: 0.04 },
	gain: 0.09,
};
export const complete: SoundDefinition = {
	source: { type: "sine", frequency: { start: 880, end: 1046 } },
	envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
	gain: 0.09,
};
export const loading: SoundDefinition = {
	source: { type: "sine", frequency: 700 },
	envelope: { attack: 0.005, decay: 0.08, sustain: 0.01, release: 0.03 },
	gain: 0.06,
};
export const tap: SoundDefinition = {
	source: { type: "sine", frequency: 1400 },
	envelope: { attack: 0, decay: 0.01, sustain: 0, release: 0.003 },
	gain: 0.09,
};
export const press: SoundDefinition = {
	source: { type: "sine", frequency: 1200 },
	envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
	gain: 0.08,
};
export const release: SoundDefinition = {
	source: { type: "sine", frequency: 1000 },
	envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.008 },
	gain: 0.06,
};
export const drag: SoundDefinition = {
	source: { type: "sine", frequency: 900 },
	envelope: { attack: 0.003, decay: 0.05, sustain: 0.01, release: 0.02 },
	gain: 0.05,
};
export const drop: SoundDefinition = {
	source: { type: "sine", frequency: { start: 900, end: 600 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const select: SoundDefinition = {
	source: { type: "sine", frequency: 1300 },
	envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.008 },
	gain: 0.08,
};
export const deselect: SoundDefinition = {
	source: { type: "sine", frequency: 1100 },
	envelope: { attack: 0, decay: 0.018, sustain: 0, release: 0.007 },
	gain: 0.06,
};
export const focus: SoundDefinition = {
	source: { type: "sine", frequency: 1200 },
	envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.006 },
	gain: 0.04,
};
export const blur: SoundDefinition = {
	source: { type: "sine", frequency: 1000 },
	envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.005 },
	gain: 0.03,
};
export const forward: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 800 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.08,
};
export const open: SoundDefinition = {
	source: { type: "sine", frequency: { start: 500, end: 1000 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const close: SoundDefinition = {
	source: { type: "sine", frequency: { start: 1000, end: 500 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.06,
};
export const expand: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 800 } },
	envelope: { attack: 0.003, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.06,
};
export const collapse: SoundDefinition = {
	source: { type: "sine", frequency: { start: 800, end: 600 } },
	envelope: { attack: 0.003, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.06,
};
export const tab: SoundDefinition = {
	source: { type: "sine", frequency: 1100 },
	envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.008 },
	gain: 0.07,
};
export const swipe: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 1200 } },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.06,
};
export const confirm: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 1000 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.09,
};
export const cancel: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 500 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const deny: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 300 } },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.08,
};
export const undo: SoundDefinition = {
	source: { type: "sine", frequency: { start: 900, end: 700 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const redo: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 900 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const alert: SoundDefinition = {
	source: { type: "sine", frequency: 880 },
	envelope: { attack: 0, decay: 0.1, sustain: 0.02, release: 0.04 },
	gain: 0.1,
};
export const message: SoundDefinition = {
	source: { type: "sine", frequency: 1046 },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.08,
};
export const reminder: SoundDefinition = {
	source: { type: "sine", frequency: 784 },
	envelope: { attack: 0, decay: 0.12, sustain: 0.02, release: 0.04 },
	gain: 0.09,
};
export const mention: SoundDefinition = {
	source: { type: "sine", frequency: 1100 },
	envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
	gain: 0.08,
};
export const show: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 900 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.06,
};
export const hide: SoundDefinition = {
	source: { type: "sine", frequency: { start: 900, end: 600 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.05,
};
export const slide: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 1100 } },
	envelope: { attack: 0.005, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.06,
};
export const fade: SoundDefinition = {
	source: { type: "sine", frequency: 800 },
	envelope: { attack: 0.01, decay: 0.12, sustain: 0, release: 0.04 },
	gain: 0.05,
};
export const pop: SoundDefinition = {
	source: { type: "sine", frequency: { start: 500, end: 200 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.09,
};
export const clear: SoundDefinition = {
	source: { type: "sine", frequency: { start: 1000, end: 600 } },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.07,
};
export const remove: SoundDefinition = {
	source: { type: "sine", frequency: { start: 800, end: 400 } },
	envelope: { attack: 0, decay: 0.07, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const trash: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 250 } },
	envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
	gain: 0.08,
};
export const shred: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 200 } },
	envelope: { attack: 0, decay: 0.12, sustain: 0, release: 0.04 },
	gain: 0.09,
};
export const upload: SoundDefinition = {
	source: { type: "sine", frequency: { start: 500, end: 1000 } },
	envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
	gain: 0.08,
};
export const download: SoundDefinition = {
	source: { type: "sine", frequency: { start: 1000, end: 500 } },
	envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
	gain: 0.08,
};
export const refresh: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 900 } },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.07,
};
export const sync: SoundDefinition = {
	source: { type: "sine", frequency: 880 },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.08,
};
export const process: SoundDefinition = {
	source: { type: "sine", frequency: 750 },
	envelope: { attack: 0.005, decay: 0.1, sustain: 0.01, release: 0.03 },
	gain: 0.06,
};
export const cut: SoundDefinition = {
	source: { type: "sine", frequency: 1300 },
	envelope: { attack: 0, decay: 0.01, sustain: 0, release: 0.004 },
	gain: 0.08,
};
export const snapshot: SoundDefinition = {
	source: { type: "sine", frequency: 1200 },
	envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.006 },
	gain: 0.09,
};
export const lock: SoundDefinition = {
	source: { type: "sine", frequency: { start: 800, end: 600 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.08,
};
export const unlock: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 900 } },
	envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
	gain: 0.08,
};
export const enable: SoundDefinition = {
	source: { type: "sine", frequency: { start: 700, end: 1000 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const disable: SoundDefinition = {
	source: { type: "sine", frequency: { start: 1000, end: 700 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.06,
};
export const connect: SoundDefinition = {
	source: { type: "sine", frequency: { start: 600, end: 1100 } },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.08,
};
export const disconnect: SoundDefinition = {
	source: { type: "sine", frequency: { start: 1100, end: 600 } },
	envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
	gain: 0.07,
};
export const mute: SoundDefinition = {
	source: { type: "sine", frequency: { start: 900, end: 500 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.07,
};
export const unmute: SoundDefinition = {
	source: { type: "sine", frequency: { start: 500, end: 900 } },
	envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
	gain: 0.08,
};
export const record: SoundDefinition = {
	source: { type: "sine", frequency: 660 },
	envelope: { attack: 0.005, decay: 0.08, sustain: 0.02, release: 0.03 },
	gain: 0.08,
};
export const capture: SoundDefinition = {
	source: { type: "sine", frequency: 1100 },
	envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.008 },
	gain: 0.09,
};

export const _patch: SoundPatch = {
	...{
		name: "Minimal",
		author: "Om Mishra",
		version: "1.0.0",
		description:
			"Clean, understated UI sounds with short envelopes and low gain — subtle feedback that stays out of the way",
		tags: ["ui", "minimal", "subtle", "clean", "quiet"],
	},
	sounds: {
		success,
		error,
		warning,
		info,
		click,
		back,
		enter,
		delete: _delete,
		copy,
		paste,
		scroll,
		hover,
		toggle,
		notify,
		complete,
		loading,
		tap,
		press,
		release,
		drag,
		drop,
		select,
		deselect,
		focus,
		blur,
		forward,
		open,
		close,
		expand,
		collapse,
		tab,
		swipe,
		confirm,
		cancel,
		deny,
		undo,
		redo,
		alert,
		message,
		reminder,
		mention,
		show,
		hide,
		slide,
		fade,
		pop,
		clear,
		remove,
		trash,
		shred,
		upload,
		download,
		refresh,
		sync,
		process,
		cut,
		snapshot,
		lock,
		unlock,
		enable,
		disable,
		connect,
		disconnect,
		mute,
		unmute,
		record,
		capture,
	},
};
